const DATABASE_NAME = '@smartfinances';

//@app:collection

const COLLECTION_HIGHLIGHTDATA = `${DATABASE_NAME}:highlightdata`
const COLLECTION_TRANSACTIONS = `${DATABASE_NAME}:transactions`
const COLLECTION_TOKENS = `${DATABASE_NAME}:token`
const COLLECTION_USERS = `${DATABASE_NAME}:user`

export {
  COLLECTION_HIGHLIGHTDATA,
  COLLECTION_TRANSACTIONS,
  COLLECTION_TOKENS,
  COLLECTION_USERS
}